version: '2'

services:
  webapplication1:
    image: webapplication1
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile      
    depends_on:
      - redis_db
  redis_db:
    image: redis
    ports:
      - "6379"